# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "https://github.com/BlaizingInfernoDragon123/More-On-Html/new/main?dependabot_template=1&filename=.github%2Fdependabot.yml" # See documentation for possible values
    directory: "https://github.com/BlaizingInfernoDragon123/More-On-Html/new/main?dependabot_template=1&filename=.github%2Fdependabot.yml" # Location of package manifests
    schedule:
      interval: "weekly"
